version: '3.8'

services:
  app:
    image: laipuni/todoapp:backend-dev # 백엔드 애플리케이션 Docker 이미지
    container_name: backend-app
    ports:
      - "8080:8080" # 애플리케이션을 로컬의 8080 포트에 연결
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/todoapp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 100101
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-db
      - redis

  redis:
    image: redis:latest
    container_name: local-redis
    ports:
      - "6379:6379"

  mysql-db:
    image: mysql:8.0
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 100101  # root 사용자 비밀번호 설정
      MYSQL_DATABASE: todoapp
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
